apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-etcd
  annotations:
    kubectl.kubernetes.io/change-cause: "Automatic redeployment triggered by Jenkins" # Thêm annotation để ghi chú lý do triển khai
spec:
  selector:
    matchLabels:
      app: spring-etcd
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-etcd
    spec:
      containers:
        - name: spring-etcd
          image: hub.thangnotes.net/spring-etcd:latest
          ports:
            - containerPort: 1234
#          readinessProbe:
#            httpGet:
#              path: /actuator/health # Điều chỉnh đường dẫn kiểm tra sự sẵn sàng tại đây
#              port: 1234
#          livenessProbe:
#            httpGet:
#              path: /actuator/health # Điều chỉnh đường dẫn kiểm tra sự sống tại đây
#              port: 1234

---
apiVersion: v1
kind: Service
metadata:
  name: spring-etcd-loadbalancer
spec:
  selector:
    app: spring-etcd
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234

