apiVersion: apps/v1
kind: Deployment
metadata:
  name: springk8s
spec:
  selector:
    matchLabels:
      app: springk8s
  replicas: 3
  template:
    metadata:
      labels:
        app: springk8s
    spec:
      containers:
        - name: springk8s
          image: hub.thangnotes.net/springk8s
          ports:
            - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: springk8s-loadbalancer
spec:
  selector:
    app: springk8s
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
