apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: springk8s
spec:
  selector:
    matchLabels:
      app: springk8s
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: springk8s
    spec:
      containers:
        - name: springk8s
          image: hub.thangnotes.net/springk8s # Image that will be used to containers in the cluster

          ports:
            - containerPort: 1234 # The port that the container is running on in the cluster