pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('checkout project') {
            steps {
                checkout scm
            }
        }
        stage('build project') {
            steps {
                // Run Maven on a Unix agent.
                sh "mvn clean install -DskipTests"
            }
        }
        stage('Delete old docker') {
                            steps {
                                script {
                                  // Kiểm tra xem Docker image có tồn tại hay không
                                  def imageExists = sh script: "docker image inspect docker_k8s", returnStatus: true
                                  if (imageExists == 0) {
                                   // Nếu image tồn tại, xóa nó trước khi lưu
                                      sh "docker rmi docker_k8s"
                                     }


                               }
                            }
                        }
        stage('Build Docker Image') {

                    steps {
                        sh "docker ps"
                        script {
                            sh "cd cicd"
                            sh "docker build -t docker_k8s ."
                        }
                    }
                }
                stage('Save Docker Image') {
                    steps {
                        script {
                           // Lưu Docker image thành file tar
                           sh "docker save -o docker_k8s.tar docker_k8s"
                       }
                    }
                }
    }
}
